import { useEffect, useState } from "react";
import { collection, getDocs, query, where } from "firebase/firestore";
import { useNavigate, useParams } from "react-router-dom";
import { db } from "../firebase/config";

const sections = {
  "Campus & Main Facilities": ["campusWall", "campusWallHeight", "numberOfEntryGates", "cctvAtEntryGates", "numberOfConferenceHalls", "numberOfSmartClassroom", "auditoriums", "electricityBackup", "grounds", "lectureTheatre", "computerLabs", "medicalClinic", "indoorSports", "outdoorSports", "cafeterias", "drinkingWater", "studentClubs", "innovationCenter", "incubationCentre", "laboratories", "gym", "generalShops", "swimmingPool"],
  "Library": ["totalNumberOfBooks", "journals", "eLibrary", "readingHallCapacity"],
  "Staff & Support": ["femaleStaff", "maleStaff", "femaleMTS", "maleMTS", "femaleGuard", "maleGuard"],
  "Equipment & Connectivity": ["photocopier", "printer", "internetConnectivity", "totalNumberOfComputers"],
  "Sports Facilities": ["chess", "tableTennis", "carrom", "football", "cricket", "badminton", "outdoorBadminton", "squash", "athletics", "snooker", "basketball", "tableFootball", "tennis", "indoorBasketball", "hockey"],
};
const labels = { campusWall: "Campus Wall", campusWallHeight: "Campus Wall Height", numberOfEntryGates: "Entry Gates", cctvAtEntryGates: "CCTV at Entry Gates", numberOfConferenceHalls: "Conference Halls", numberOfSmartClassroom: "Smart Classrooms", auditoriums: "Auditoriums", electricityBackup: "Electricity Backup", grounds: "Grounds", lectureTheatre: "Lecture Theatres", computerLabs: "Computer Labs", medicalClinic: "Medical Clinic", indoorSports: "Indoor Sports", outdoorSports: "Outdoor Sports", cafeterias: "Cafeterias", drinkingWater: "Drinking Water", studentClubs: "Student Clubs", innovationCenter: "Innovation Center", incubationCentre: "Incubation Centre", laboratories: "Laboratories", gym: "GYM", generalShops: "General Shops", swimmingPool: "Swimming Pool", totalNumberOfBooks: "Total Books", journals: "Journals", eLibrary: "E-Library", readingHallCapacity: "Reading Hall Capacity", femaleStaff: "Female Staff", maleStaff: "Male Staff", femaleMTS: "Female MTS", maleMTS: "Male MTS", femaleGuard: "Female Guard", maleGuard: "Male Guard", photocopier: "Photocopiers", printer: "Printers", internetConnectivity: "Internet Connectivity", totalNumberOfComputers: "Total Computers", chess: "Chess", tableTennis: "Table Tennis", carrom: "Carrom", football: "Football", cricket: "Cricket", badminton: "Badminton", outdoorBadminton: "Outdoor Badminton", squash: "Squash", athletics: "Athletics", snooker: "Snooker", basketball: "Basketball", tableFootball: "Table Football", tennis: "Tennis", indoorBasketball: "Indoor Basketball", hockey: "Hockey" };

export default function ChancellorInfrastructure() {
  const { university } = useParams(); const navigate = useNavigate(); const universityName = decodeURIComponent(university); const [data, setData] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { (async () => { try { const snapshot = await getDocs(query(collection(db, "infrastructureDetails"), where("UniversityName", "==", universityName))); setData(snapshot.empty ? null : snapshot.docs[0].data()); } catch (e) { console.error(e); setError("Unable to load infrastructure data."); } finally { setLoading(false); } })(); }, [universityName]);
  return <div className="min-h-screen bg-slate-100 text-slate-900"><header className="bg-slate-950 text-white px-5 md:px-8 py-5"><div className="max-w-7xl mx-auto flex justify-between gap-4"><div><button onClick={() => navigate(`/chancellor/${encodeURIComponent(universityName)}`)} className="inline-flex items-center gap-2 rounded-md border border-slate-700 px-3 py-2 text-sm font-medium text-slate-100 hover:bg-slate-800 transition-colors mb-4">← Back to {universityName}</button><h1 className="text-3xl font-black">Infrastructure</h1><p className="text-slate-400 mt-1">Campus, library, support and sports facilities</p></div></div></header><main className="max-w-7xl mx-auto px-4 md:px-6 py-7">{error && <div className="p-4 rounded-xl bg-red-50 border border-red-200 text-red-700 mb-5">{error}</div>}{loading ? <div className="bg-white rounded-xl border p-10 text-center text-slate-500">Loading infrastructure...</div> : !data ? <div className="bg-white rounded-xl border p-10 text-center text-slate-500">No infrastructure data available.</div> : Object.entries(sections).map(([title, keys]) => <section key={title} className="mb-7"><h2 className="text-xl font-black mb-4">{title}</h2><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">{keys.map((key) => <div key={key} className="bg-white rounded-xl border p-4 shadow-sm"><p className="text-xs text-slate-500">{labels[key]}</p><p className="font-bold mt-2 break-words">{data[key] ?? "-"}</p></div>)}</div></section>)}</main></div>;
}
