import { useEffect, useState } from "react";
import { collection, getDocs, query, where } from "firebase/firestore";
import { useNavigate, useParams } from "react-router-dom";
import { db } from "../firebase/config";

const columns = [["Floor", "Floor"], ["totalClassroom", "Total Classrooms"], ["classrooms", "Classrooms"], ["corridor", "Corridor"], ["washroomMale", "Male Washrooms"], ["washroomFemale", "Female Washrooms"], ["pwdProvision", "PWD Provision"], ["pwdTotalSeats", "PWD Seats"], ["pwdWashrooms", "PWD Washrooms"], ["pwdRamps", "PWD Ramps"], ["lift", "Lift"]];

export default function ChancellorCapacity() {
  const { university } = useParams(); const navigate = useNavigate(); const universityName = decodeURIComponent(university);
  const [rows, setRows] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { (async () => { try { const snapshot = await getDocs(query(collection(db, "capacity"), where("UniversityName", "==", universityName))); setRows(snapshot.docs.map((item) => ({ id: item.id, ...item.data() }))); } catch (e) { console.error(e); setError("Unable to load capacity data."); } finally { setLoading(false); } })(); }, [universityName]);
  return <div className="min-h-screen bg-slate-100 text-slate-900"><header className="bg-slate-950 text-white px-5 md:px-8 py-5"><div className="max-w-7xl mx-auto flex flex-col md:flex-row md:justify-between gap-4"><div><button onClick={() => navigate(`/chancellor/${encodeURIComponent(universityName)}`)} className="inline-flex items-center gap-2 rounded-md border border-slate-700 px-3 py-2 text-sm font-medium text-slate-100 hover:bg-slate-800 transition-colors mb-4">← Back to {universityName}</button><h1 className="text-3xl font-black">Capacity</h1><p className="text-slate-400 mt-1">Floor-wise classroom and accessibility capacity</p></div></div></header><main className="max-w-7xl mx-auto px-4 md:px-6 py-7">{error && <div className="p-4 rounded-xl bg-red-50 border border-red-200 text-red-700 mb-5">{error}</div>}{loading ? <div className="bg-white rounded-xl border p-10 text-center text-slate-500">Loading capacity data...</div> : !rows.length ? <div className="bg-white rounded-xl border p-10 text-center text-slate-500">No capacity data available.</div> : <div className="bg-white rounded-xl shadow-sm border overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[1300px] text-sm"><thead className="bg-slate-900 text-white"><tr><th className="p-3">#</th>{columns.map(([, label]) => <th key={label} className="p-3 text-left whitespace-nowrap">{label}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={row.id} className="border-b hover:bg-slate-50"> <td className="p-3 text-slate-400">{index + 1}</td>{columns.map(([key]) => <td key={key} className="p-3">{row[key] ?? "-"}</td>)}</tr>)}</tbody></table></div></div>}</main></div>;
}
